# AUTOGENERATED! DO NOT EDIT! File to edit: ../cats_dogs.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% ../cats_dogs.ipynb 3
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% ../cats_dogs.ipynb 9
learn = load_learner('model.pkl')

# %% ../cats_dogs.ipynb 11
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% ../cats_dogs.ipynb 14
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['dog.jfif', 'cat.jfif', 'dunno.jfif']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False, share=True)
